# Generated by Django 3.1.1 on 2020-11-02 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201031_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='all_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
