# Generated by Django 3.1.1 on 2020-11-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201102_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='counter',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
